### ISSUE TITLE
Support ES6 syntax

### ISSUE THREAD

**Issue by THernandez03** [7ute/symbols-list#1]
First of all, this is a great plugin for Atom. but i think it could be better getting the same tags as [atom/symbols-view](https://github.com/atom/symbols-view).

**Comment by 7ute** [comment]
First of all, thanks!
I deliberately omitted most tags and did not reuse symbols-view tag detection to have a light sidebar, close to the one present on Panic's Coda "code navigator".
You may want to check https://github.com/xndcn/symbols-tree-view , which uses symbols-view tag-generator.

The languages added are the ones I use daily, but the list is meant be extended.
Also, what tag syntax from ES6 would you like to see implemented?

**Comment by THernandez03** [comment]
i think modules with this structure

```
(function(){
  'use strict';

  class Sidebar extends Class{
    static myVar = 'initialized';
    static myOtherVar = '';

    constructor(){
    }
    something(){
    }
    somethingElse(){
    }
  }
}());
```

to get `constructor`, `something`, `somethingElse` as functions and `myVar` and `myOtherVar` as variables

**Comment by 7ute** [comment]
OK. I added the methods, but not the vars, again to keep the sidebar light on heavy projects :)
I may put some settings some day, to choose which symbol keep for each language, and tweak the sidebar a little.
Whenever i do this, i'll add variables and properties regex.

**Comment by THernandez03** [comment]
It works great... thanks so much. To make a contribution, do you have some rules to follow ??

**Comment by 7ute** [comment]
You're welcome.
No other rule than "Keep it light", to preserve it's main purpose : see the code structure at a glance, and navigate quickly through it.
Feel free to add your regexes and the languages you use, and make pull requests.
