### ISSUE TITLE
Support for getters/setters.

### ISSUE THREAD

**Issue by trusktr** [7ute/symbols-list#15]
The plugin shows classes and class methods, but it doesn't show getters/setters. For example, in the following, the symbols list doesn't show bar, only foo:

``` js
class SomeClass {
  foo() {}
  set bar(value) {}
  get bar() {}
}
```

The actual result is:

![screen shot 2016-06-12 at 3 38 42 pm](https://cloud.githubusercontent.com/assets/297678/15994219/c72d8cc6-30b3-11e6-96c9-cc58f76a4b5e.png)

It could be something like (made in Gimp, but you get the idea):

![screen shot 2016-06-12 at 3 38 42 pm2](https://cloud.githubusercontent.com/assets/297678/15994285/c39d5a9a-30b4-11e6-979d-7a50d63f3574.png)

**Comment by mbuc82** [comment]
Hello @trusktr ,

for what language do you need this? I guess this would be easy to achieve...

Regards

**Comment by trusktr** [comment]
Hi @mbuc82, it's for JavaScript.

**Comment by trusktr** [comment]
It would be awesome!

**Comment by mbuc82** [comment]
Hello @trusktr ,

i've added symbols for getters and setters, they will be included in the upcoming release.
Please let me know, if you face any further problems. Until then i would close this issue.

Regards
