### ISSUE TITLE
Language CSS / SCSS

### ISSUE THREAD

**Issue by neolao** [7ute/symbols-list#22]
I tried with a CSS file, it does not display anything.

Also, it would be great to support SCSS too.

**Comment by 7ute** [comment]
Actually, as the CSS markup isn't hierarchical, or structured, it's a bit hard to choose symbols.
However, you can use Panic's Coda labeled comments ( comment with an exclamation mark ) to put your own symbols in stylesheets :
`/* ! This is a label comment */`

Of course, SCSS and LESS can be great. I'll add it to my TODO.

**Comment by Albertc** [comment]
How is that? Is going to be possible someday.

It seems that now is not working

Thanks

**Comment by 7ute** [comment]
It's working on SCSS and CSS.
If not, could you provide a test case? Thanks :)
