### ISSUE TITLE
Unicode symbol not being recognized

### ISSUE THREAD

**Issue by joonro** [7ute/symbols-list#28]
Hi,

It seems symbols-list does not recognize any symbols with unicode characters that I have in my Python 3 code in the view. For example, the following function does not show up in the list:

``` python
def test_unicode_θ():
    pass
```

Thank you!

**Comment by mbuc82** [comment]
Hello joonro,

i've improved the regular expressions for python, so that also unicode characters are recognized for classes, class methods as well as function names. The fix will be included within the next release.

Regards

Marco

**Comment by joonro** [comment]
Thank you so much for the fix! Looking forward to using it.
