### ISSUE TITLE
[idea] Hide when No matches found

### ISSUE THREAD

**Issue by 50l3r** [7ute/symbols-list#29]
I have a idea,

Hide a sidebar when not matches found.
Hide sidebar in settings panel.

**Comment by 7ute** [comment]
And that's a good idea :)

**Comment by mbuc82** [comment]
Hello 50l3r,

there is a new config setting "Hide On Empty List" in the upcoming release, which lets the panel disappear, if no matches are found. The panel also disappers when no text editor is visible (like in the settings view).
