### ISSUE TITLE
ERROR & SOLUTION: On Save error occurs

### ISSUE THREAD

**Issue by Joseffb** [7ute/symbols-list#30]
I get this error when I save a file.

Failed to spawn command /Users/joseffb/.atom/packages/symbols-view-plus/vendor/ctags-darwin. Make sure /Users/joseffb/.atom/packages/symbols-view-plus/vendor/ctags-darwin is installed and on your PATH

Solved when you install the plugin symbols-view-plus

**Comment by 7ute** [comment]
Hi, thanks for your feedback.
Yet, I'm unable to reproduce said error, and I don't have "symbols-view-plus".
It may be linked to this : https://github.com/xndcn/symbols-tree-view/issues/110 which was solved with a restart of Atom after the update.
