### ISSUE TITLE
Feature request: sorting

### ISSUE THREAD

**Issue by franksl** [7ute/symbols-list#4]
Hello,
An option to allow symbols list sorting would be veeeeeery nice!
Thanks,
Frank

**Comment by 7ute** [comment]
That's a goooooood idea!
I added a switch between line and alphabetical ordering in the settings :)
Just let me know if you think of something more specific.

**Comment by franksl** [comment]
Great! 
Thank you,
Frank

**Comment by jbiskofski** [comment]
Hi, i cant find this setting. Im new to atom, 
Im in Settings > Packages > symbols-view > Settings

The only settings I see are, "quick jump to file symbol", "use editor grammar", keybindings:enable

Am I missing something? thanks!
