### ISSUE TITLE
support cache for huge files

### ISSUE THREAD

**Issue by pmgouveia** [7ute/symbols-list#47]
everytime im navigating trough my files, the atom editor hiccups, because all of the files are really huge, and it seems that the symbols-list doesn't cache anything.

great plugin!

**Comment by mbuc82** [comment]
Hello @pmgouveia ,

the generated symbols-list will now be cached and just re-generated, if the source has been modified.
The improvements will be included in the upcoming version. 
I'll close this issue for now, but feel free to re-open it, if you face any further problems.

Regards
Marco
