### ISSUE TITLE
Symbols go missing when toggling the list

### ISSUE THREAD

**Issue by nterms** [7ute/symbols-list#5]
First of all, thank you for the nice plugin. But when I toggle the list with menu, it does not re-render the symbols list automatically. I had to switch the files to get the list back. Also any idea how we can toggle the list with a hot key?

**Comment by 7ute** [comment]
Thanks for the feedback. However can't seem to reproduce the bug. 
Maybe is it a key binding conflict? The plugins defaults binding for toggling is cmd+alt+L .

**Comment by nterms** [comment]
OK, it works after I restart Atom. Thanks for the hotkey.
