### ISSUE TITLE
blocks editor when loading

### ISSUE THREAD

**Issue by pmgouveia** [7ute/symbols-list#56]
everytime I change tab, the editor gets blocked because its loading the symbols list.

I have files with 4000 lines of code, which makes it really slow

**Comment by mbuc82** [comment]
Hello @pmgouveia ,

within the current master, there is already a fix for this behavior,
to just reload the symbols list, if it is really needed.

Please see: https://github.com/7ute/symbols-list/commit/d58319177a5716fc5f79d83b3f2ea1e264c49577

It will be included within the upcoming version.

Best regards
Marco
