### ISSUE TITLE
Javascript Es6Methods with spaces before parenthesis are not recognized 

### ISSUE THREAD

**Issue by FelixBrendel** [7ute/symbols-list#58]
If you add `\s*`  
inside the 
`es6method: /^[^\S\n]*(?:[*][\s\n]+)?(?:async[\s\n]+)?(?!foreach|if|for|while|catch)([\w]+\(.*\))[\s\n]*{/gmi`
it becomes
`es6method: /^[^\S\n]*(?:[*][\s\n]+)?(?:async[\s\n]+)?(?!foreach|if|for|while|catch)([\w]+\s*\(.*\))[\s\n]*{/gmi`
and the methods are recognized correctly.

**Comment by mbuc82** [comment]
Hello @FelixBrendel ,

thanks a lot for your contribution. The fix will be included in the upcoming release.

Best regards
Marco
