### ISSUE TITLE
Feature Request : Set line position in the middle of the screen

### ISSUE THREAD

**Issue by dimitrik-fr** [7ute/symbols-list#59]
Currently on click of the symbol name, the corresponding line position will appear on top of the screen (moving up) or bottom of the screen (moving down).. -- would be great just to place the position in the middle of the screen - similar to what we have with Ctrl-G in Atom (or add an option according to what the users prefer).

Thanks a lot for the great stuff !!

Rgds,
-Dimitri

**Comment by mbuc82** [comment]
Hello @dimitrik-fr ,

this feature is already implemented in the master and will be part of the upcoming version.
Please see https://github.com/7ute/symbols-list/commit/79631fa5a83cb8cf3f53e55d7348f14c5d671d35

Best regards
Marco
