### ISSUE TITLE
Detect functions within an object

### ISSUE THREAD

**Issue by giedrius-timinskis** [7ute/symbols-list#6]
Hey,

The codebase I'm working in is written in Backbone, so it'd be great to have support for functions declared within an object:

```
return Backbone.Model.extend({
    SOME_VAR: 'some info',
    someFunction: function () {
        return false;
    } 
});
```

If you're super busy I might look into adding this on a weekend as well

**Comment by 7ute** [comment]
Yup i'll give it a look when i have a few minutes :)

**Comment by 7ute** [comment]
Done in the latest release.

**Comment by giedrius-timinskis** [comment]
Works perfectly, thanks a lot!
