### ISSUE TITLE
Language Support Latex

### ISSUE THREAD

**Issue by Joinyy** [7ute/symbols-list#61]
Latex would be great, as the Symbols-tree-view Package is no longer maintained.

It covers Chapters, Sections (sub&subsub) and labels. Would be the point for me, where I use symbols-list over the old package.

Regex should be really easy, as everything in LaTeX begins with `\` followed by either `chapter{NAME}`,`section{NAME}`,`subsection{NAME}`,`subsubsection{NAME}`,`label{NAME}` and so on. Maybe the sections in a chapter could be desplayed like class members in a oo programming language, and the subsections and subsubsections so on. Labels the same, but with a different icon.

**Comment by 7ute** [comment]
Hi,

The support for LaTeX syntax will be available on the next release.
I added `chapter`, `section`, `subsection` and `subsubsection`.
