### ISSUE TITLE
Q : Using dev version ?

### ISSUE THREAD

**Issue by dimitrik-fr** [7ute/symbols-list#62]
Is there any "proper" way to use "dev" version ?.. -- seems like there are several long awaited features already developed, and it'll be great to let validate them before the next release is shipped..

Rgds,
-Dimitri

**Comment by mbuc82** [comment]
Hi @dimitrik-fr ,

you could check out the master branch (which is the "dev" version), cd to your local repository and link it with "apm link" or either "apm link -d" to link it as a development package. If linked as dev-package, start atom with atom -d to either load the linked dev packages.

Best regards
Marco

**Comment by dimitrik-fr** [comment]
Hi Marco,

works just fine !! 

also, Atom (1.19) is reporting there is a deprecation in the code : instead of TextEditor.setScrollTop() the TextEditorElement::setScrollTop should be used instead.

but all in all, new changes rock !! - no blinking anymore on tab switch, configurable line positioning and panel width, really cool !! kudos !!! ;-))

Rgds,
-Dimitri
