### ISSUE TITLE
sidebar keeps coming back when toggled off

### ISSUE THREAD

**Issue by joachim-n** [7ute/symbols-list#63]
To reproduce:

- open two files
- open the sidebar 
- toggle the sidebar off with cmd-alt-l. The sidebar hides.
- switch to the other file. The sidebar shows again. (I don't know is this is a bug or not -- is the toggle per-file?)
- switch to the first file. The sidebar is back.

**Comment by mbuc82** [comment]
Hello @joachim-n ,

today symbols-list 2.5.1 was released, which fixes this problem. I'll close this issue for now.

Have a nice day!

Cheers,
Marco
