### ISSUE TITLE
Alphabetical sorting doesn't work

### ISSUE THREAD

**Issue by Kerfred** [7ute/symbols-list#68]
Wether I tick the Alphabetical Sorting checkbox or not, the symbol list is not sorted alphabetically.
For information, I am editing PHP files.
I have tried to restart Atom and to close and re-open the file, but same thing: the list is not sorted.

**Comment by BelgianShepherd** [comment]
Same here with JavaScript.  Very useful if you can get it working.

**Comment by overnitesoftware** [comment]
Same with Perl (.pl). Any solutions yet?

**Comment by overnitesoftware** [comment]
@Kerfred @BelgianShepherd 
Found it. In file symbols-list/lib/symbols-list-view.coffee line 80 you have to change this
`if atom.config.get('symbols-list.alphabeticalSorting')`
to this:
`if atom.config.get('symbols-list.basic.alphabeticalSorting')`

**Comment by MattRiddell** [comment]
Cool yeah that worked for me.

That file was in:

`~/.atom/packages/symbols-list/lib`

**Comment by rabw** [comment]
Thanks everyone, was also having this problem and the change in symbols-list-view.coffee fixed it for me.
