### ISSUE TITLE
'TODO', 'FIXME', 'HACK' words are not working in .php files

### ISSUE THREAD

**Issue by scsmash3r** [7ute/symbols-list#73]
Seems that now 'TODO', 'FIXME', 'HACK' words are not working in .php files at all.

Bare minimum:
1. Create .php file
2. Put contents:
```
<?php
/**
 * @link string
 * @copyright string
 * @license string
 */
namespace frontend\components;

use Something;

/**
 * Some big comment
 */
class SomeClass extends SomeOtherClass
{
    // TODO Some text for todo
    protected $userId = 0;


    /**
     * @inheritdoc
     */
    public function init()
    {
        /* FIXME Some text for fixme */
        parent::init();
    }
}
```
3. Save file, nothing will be added to symbols list sidebar.

_Originally posted by @scsmash3r in https://github.com/7ute/symbols-list/issues/66#issuecomment-478285519_

**Comment by scsmash3r** [comment]
Okay, it will work, if you add : after word:
```
/* FIXME: sometext */
// TODO: somtext 
```

If it's how it is intended to work, the issue can be closed.

**Comment by 7ute** [comment]
One year later ^^'
Yeah, FIXME and TODO are described with `:` in most RFC's.
